### ISSUE TITLE
multiprocessing Actor

### ISSUE THREAD

**Issue by cullender-skew** [jodal/pykka#84] opened 2019-11-19 15:09 UTC
Hi,

I am new to python and would like to build my app using pyakka (I have plenty of experience using akka). 

I have read about the pitfalls of threading and the GIL in pyhon and was wondering if it would make sense to create a `MultiProcessingActor`, as an alternative to the `ThreadActor`, which would bypass the single GIL bottleneck?

Thanks 
Daniel

**Comment by jodal** [comment] 2019-11-20 16:23
It should be quite straight forward to add a multiprocessing "runtime" to Pykka. There's already three examples showing what is needed:

- [pykka/_threading.py](https://github.com/jodal/pykka/blob/develop/pykka/_threading.py)
- [pykka/eventlet.py](https://github.com/jodal/pykka/blob/develop/pykka/eventlet.py)
- [pykka/gevent.py](https://github.com/jodal/pykka/blob/develop/pykka/gevent.py)

All of these 70-100 line long runtime implementations pass the same test suite, which is parametrized so that it very easy to add another implementation:

https://github.com/jodal/pykka/blob/1982e1caf63726c66b28616c80d548ae1bb4fe87/tests/conftest.py#L32-L41

Before embarking on this, please note that the GIL is only an issue if you're application is CPU-bound. When a Python thread does IO, the GIL is released and other threads may proceed with their work. If your application is IO-bound, I'd see how far I could get with threads or asyncio first.

**Comment by cullender-skew** [comment] 2019-11-20 16:35
thanks for the great feedback and insights, I will play around

**Comment by mcepl** [comment] 2020-01-09 15:40
This is the exact duplicate of #19, isn’t it?

**Comment by jodal** [comment] 2020-01-09 21:33
Good point! Closing as a duplicate of #19.

**Closed by jodal** 2020-01-09 21:33 UTC
